services:
  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: [ "install" ] # Comando de Composer que quieres ejecutar, por ejemplo, install o update
  web:
    image: phppinarmvc:1
    volumes:
      - ./:/var/www/html
      - ./config/php-conf:/usr/local/etc/php
      - ./config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - 80:80
    networks:
      - pinarMVCnetwork
  db:
    image: mariadb:10.4
    volumes:
      - databaseVolume:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: pinarmvcDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - pinarMVCnetwork
    ports:
      - 3306:3306

networks:
  pinarMVCnetwork:


volumes:
  databaseVolume:
