version: '3.8'

services:
  web:
    image: phpPinarMVC:1
    volumes:
      - ./:/var/www/html
      - ./config/php-conf:/usr/local/etc/php
      - ./config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - 80:80
    networks:
      - mynetwork
  db:
    image: mysql:5.7
    volumes:
      - mysqlVolume:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin 
      MYSQL_ROOT_PASSWORD: 12345678 
    networks:
      - pinarMVCnetwork 
    ports:
      - 3306:3306

networks:
  pinarMVCnetwork:

volumes:
  mysqlVolume:

